### ISSUE TITLE
POX replaceResult: oauth_body_hash

### ISSUE THREAD

**Issue by bluej100** [IMSGlobal/basiclti-util-java#3]
Sakai is rejecting replaceResult calls with "Did not find oauth_body_hash". Moodle requires it as well ( https://github.com/moodle/moodle/blob/master/mod/lti/OAuthBody.php ).

I have a WIP commit up at https://github.com/bluej100/basiclti-util-java/commit/9d6d9652655c44b2bd8425db6ce60f9cf9bf1e17#diff-d41d8cd98f00b204e9800998ecf8427e , but it breaks signing.

**Comment by kejd315** [comment]
anyone is going to fix this? I just ran into the same issue where oauth_body_hash is not calculated in the request header.

**Comment by pfgray** [comment]
Hi @kejd315, thanks for your interest in basiclti-util-java.

It would be useful to hear a bit more about how you're using this library, and where exactly it's breaking in order to help you.

What version are you currently using? Which method are you using to send POX results to the consumer? Are you also implementing against Sakai?

In recent versions, there have been measures added to allow clients to override the default signing implementation, if you choose to use your own.

**Comment by kejd315** [comment]
I am using sendReplaceResult() from https://github.com/IMSGlobal/basiclti-util-java/blob/master/src/main/java/org/imsglobal/pox/IMSPOXRequest.java
The method doesn't generate oauth_body_hash in the request header.

**Comment by bluej100** [comment]
I've submitted a pull request for the issue, @kejd315 . Sorry for the trouble.

**Comment by bluej100** [comment]
If you're curious, @pfgray , the only problem with my previous patch was that I had to URL-encode the hash value. Embarrassing.

**Comment by kejd315** [comment]
This is great news. Regarding the body hash algorithm SHA1 you use, should it be HMAC-SHA1
 according to LTI 1.1 spec?

**Comment by bluej100** [comment]
Thanks for the review! The oauth body hash extension specifies an unkeyed
hash algorithm:

https://oauth.googlecode.com/svn/spec/ext/body_hash/1.0/oauth-bodyhash.html#unkeyed

**Comment by kejd315** [comment]
Thanks for your quick response. This looks good!
